### ISSUE TITLE
npm i failure

### ISSUE THREAD

**Issue by pplmx** [tonlabs/gosh#85]
# npm i failure
Hi, there
I have some error as follows, Could you give me some help? Thanks a lot.

## env
```shell
node: v18.0.0
os: macos 12.3.1
arch: arm
```

## FYI
<details>
<summary>Error message</summary>
npm ERR! code 1
npm ERR! path /private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! TOUCH Release/obj.target/acquireOpenSSL.stamp
npm ERR! ACTION binding_gyp_configureLibssh2_target_configure .
npm ERR! [nodegit] Configuring libssh2.
npm ERR! TOUCH Release/obj.target/configureLibssh2.stamp
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/failalloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/stdalloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_graph.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/custom_tls.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/alloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_entries.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_mem.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_snapshot.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/email.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetchhead.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filebuf.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/futils.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filter.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/graph.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/sha1.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/ubc_check.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/collisiondetect.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hashsig.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ident.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/idxmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ignore.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/index.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/indexer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/libgit2.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mailmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/midx.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_driver.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/message.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mwindow.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/net.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/netops.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/notes.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object_api.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_loose.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_mempack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_pack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/offmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oid.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidarray.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/path.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pathspec.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pool.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/posix.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pqueue.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/proxy.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/push.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reader.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/rebase.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb_fs.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reflog.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refs.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refspec.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/regexp.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/remote.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/repository.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reset.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revert.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revparse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revwalk.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/runtime.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/signature.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/socket.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl_legacy.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sortedcache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/stash.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/status.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strarray.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/mbedtls.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/registry.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/submodule.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sysdir.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tag.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/thread.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/threadstate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trace.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trailer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transaction.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transport.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/credential_helpers.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/credential.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/git.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/local.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/httpclient.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_pkt.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_protocol.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/ssh.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree-cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tsort.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/util.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/utf8.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/varint.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/vector.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/wildmatch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/worktree.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xdiffi.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xemit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xhistogram.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xmerge.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xpatience.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xprepare.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xutils.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/zstream.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/stransport.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/http.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_negotiate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_ntlm.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/tls.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/map.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/pthread.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/realpath.o
npm ERR! LIBTOOL-STATIC Release/git2.a
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/adler32.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/crc32.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/deflate.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inffast.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inflate.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inftrees.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/trees.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/zutil.o
npm ERR! LIBTOOL-STATIC Release/zlib.a
npm ERR! CC(target) Release/obj.target/http_parser/vendor/http_parser/http_parser.o
npm ERR! LIBTOOL-STATIC Release/http_parser.a
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/18.0.0/bin/node /private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp
npm ERR! info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using
npm ERR! node@18.0.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.15-node-v108-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.15-node-v108-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for nodegit@0.28.0-alpha.15 and node@18.0.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.15-node-v108-darwin-arm64.tar.gz
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp
npm ERR! info using node-gyp@8.4.1
npm ERR! gyp
npm ERR! info using
npm ERR! node@18.0.0 | darwin | arm64
npm ERR! gyp
npm ERR! info ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info using
npm ERR! node-gyp@8.4.1
npm ERR! gyp info
npm ERR! using node@18.0.0 | darwin | arm64
npm ERR! gyp
npm ERR! info find Python using Python version 3.9.12 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp
npm ERR! info spawn args [
npm ERR! gyp info spawn args   '/private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info
npm ERR! spawn args   '-f',
npm ERR! gyp info
npm ERR! spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args
npm ERR! '-I',
npm ERR! gyp info spawn args   '/Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mystic/Library/Caches/node-gyp/18.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mystic/Library/Caches/node-gyp/18.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp
npm ERR! info ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info using
npm ERR! node-gyp@8.4.1
npm ERR! gyp
npm ERR! info using node@18.0.0 | darwin | arm64
npm ERR! gyp info
npm ERR! spawn
npm ERR! make
npm ERR! gyp
npm ERR! info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../vendor/libssh2/src/agent.c:40:
npm ERR! In file included from ../vendor/libssh2/src/libssh2_priv.h:141:
npm ERR! In file included from ../vendor/libssh2/src/crypto.h:42:
npm ERR! In file included from ../vendor/libssh2/src/openssl.h:42:
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/opensslconf.h:9
npm ERR! :
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/./opensslconf_asm.h:107:
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/./archs/darwin64-arm64-cc/asm/include/openssl/opensslconf.h:13:
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/opensslv.h:4:
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/./opensslv_asm.h:21:
npm ERR! In file included from /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/./archs/darwin64-arm64-cc/asm/include/openssl/opensslv.h:109:
npm ERR! /Users/mystic/Library/Caches/node-gyp/18.0.0/include/node/openssl/macros.h:155:4: error: "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
npm ERR! #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
npm ERR!    ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/libssh2/vendor/libssh2/src/agent.o] Error 1
npm ERR! gyp
npm ERR!
npm ERR! ERR!
npm ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR!
npm ERR! stack
npm ERR! at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp
npm ERR! ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/18.0.0/bin/node" "/private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp
npm ERR! ERR! cwd /private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit
npm ERR! gyp ERR!
npm ERR! node -v v18.0.0
npm ERR! gyp ERR! node-gyp -v
npm ERR! v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp
npm ERR! ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/18.0.0/bin/node /private/var/tmp/gosh/git-remote-gosh/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/tmp/gosh/git-remote-gosh/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR!
npm ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp
npm ERR! ERR! System Darwin 21.4.0
npm ERR! node-pre-gyp
npm ERR! ERR! command "/opt/homebrew/Cellar/node/18.0.0/bin/node" "/private/var/tmp/gosh/git-remote-gosh/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp
npm ERR! ERR! cwd /private/var/tmp/gosh/git-remote-gosh/node_modules/nodegit
npm ERR! node-pre-gyp
npm ERR! ERR! node -v v18.0.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp
npm ERR! ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mystic/.npm/_logs/2022-05-14T11_51_03_836Z-debug-0.log
</details>

**Comment by awnion** [comment]
Related to https://github.com/nodegit/nodegit/issues/1840

Right now we're considering different ways to solve this. Most likely we will just rewrite git-remote-plugin for gosh on Rust 🦀

**Comment by pplmx** [comment]
Thanks, @awnion. Look forward to the version on Rust. 😄
